//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadPoint.BlogViewer.AppWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Viewer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Viewer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MadPoint.BlogViewer.AppWeb.Resources.Viewer", typeof(Viewer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string BlogListTitle {
            get {
                return ResourceManager.GetString("BlogListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog has not been found or the user has not the necessary permission to see it..
        /// </summary>
        public static string BlogNotFoundError {
            get {
                return ResourceManager.GetString("BlogNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill with the blog URL.
        /// </summary>
        public static string BlogUrlDefaultValue {
            get {
                return ResourceManager.GetString("BlogUrlDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a valid blog URL in the &quot;Blog Viewer&quot; properties of the app part..
        /// </summary>
        public static string BlogUrlError {
            get {
                return ResourceManager.GetString("BlogUrlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries body maximum length must be greater than 0..
        /// </summary>
        public static string EntriesBodyMaxLengthError {
            get {
                return ResourceManager.GetString("EntriesBodyMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string InformationTitle {
            get {
                return ResourceManager.GetString("InformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a &quot;Blog Viewer&quot; app part to the site where you want to see the blog. Edit its &quot;Blog Viewer&quot; properties, adding an existing blog URL in the same site collection of the site where you have added the app part..
        /// </summary>
        public static string InstructionsText {
            get {
                return ResourceManager.GetString("InstructionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string InstructionsTitle {
            get {
                return ResourceManager.GetString("InstructionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a trust problem between SharePoint and the app..
        /// </summary>
        public static string NotAccessTokenError {
            get {
                return ResourceManager.GetString("NotAccessTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site URL is not a blog URL because the list &quot;{0}&quot; has not been found..
        /// </summary>
        public static string NotBlogError {
            get {
                return ResourceManager.GetString("NotBlogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entries were found for this blog..
        /// </summary>
        public static string NotEntriesForThisBlog {
            get {
                return ResourceManager.GetString("NotEntriesForThisBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of entries must be greater than 0..
        /// </summary>
        public static string NumberOfEntriesError {
            get {
                return ResourceManager.GetString("NumberOfEntriesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have the necessary permissions to see this blog..
        /// </summary>
        public static string UnauthorizedError {
            get {
                return ResourceManager.GetString("UnauthorizedError", resourceCulture);
            }
        }
    }
}
